//*함수안에서 try-catch문
void func()
{
   try{
   }catch{
   }
}

//은

void func()                //함수자체의 괄호가 사라졌다!!!!!!!!!!!!!!
   try{
   }catch{
   }

이렇게 표현이 가능하다!!!!( 함수의 괄호를 안써도 가능!!! 이 기능은 생성자에서 중요하게 쓰임 ) 